name: pipeline

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run generate
      - run: "[[ -z $(git status --porcelain) ]]"
      - run: npm run type
      - run: npm run lint
      - run: npm run format
  release-check:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/master'
    steps:
      - run: true
  release:
    runs-on: ubuntu-latest
    needs: release-check
    if: contains(github.event.head_commit.message, '[release]') && !contains(github.event.head_commit.message, '[pre-release]')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npx vsce package
      - run: gh release create v$VERSION --generate-notes yaml-embedded-languages-$VERSION.vsix
        env:
          GH_TOKEN: ${{ github.token }}
      - run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
  pre-release:
    runs-on: ubuntu-latest
    needs: release-check
    if: contains(github.event.head_commit.message, '[pre-release]') && !contains(github.event.head_commit.message, '[release]')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npx vsce package --pre-release
      - run: gh release create v$VERSION --prerelease --generate-notes yaml-embedded-languages-$VERSION.vsix
        env:
          GH_TOKEN: ${{ github.token }}
      - run: npx vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
